-- ==============================================================================
-- BẾP VIỆT GOURMET - SUPABASE POSTGRESQL DATABASE SCHEMA
-- Chạy đoạn script này tại: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. BẢNG DANH MỤC MÓN ĂN
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  icon TEXT,
  display_order INTEGER DEFAULT 0
);

-- 2. BẢNG MÓN ĂN
CREATE TABLE IF NOT EXISTS foods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  image TEXT NOT NULL,
  is_available BOOLEAN DEFAULT TRUE,
  rating NUMERIC DEFAULT 5.0,
  prep_time INTEGER DEFAULT 20,
  spicy_level INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT FALSE,
  sales_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BẢNG NGƯỜI DÙNG & KHÁCH HÀNG / ADMIN
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  address TEXT,
  province TEXT,
  district TEXT,
  ward TEXT,
  role TEXT DEFAULT 'customer',
  avatar TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BẢNG ĐƠN HÀNG
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code TEXT UNIQUE NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  delivery_address TEXT NOT NULL,
  province TEXT,
  district TEXT,
  note TEXT,
  subtotal NUMERIC NOT NULL,
  discount NUMERIC DEFAULT 0,
  delivery_fee NUMERIC DEFAULT 15000,
  total_amount NUMERIC NOT NULL,
  payment_method TEXT DEFAULT 'COD',
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. BẢNG CHI TIẾT MÓN TRONG ĐƠN HÀNG
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  food_id BIGINT,
  food_name TEXT NOT NULL,
  food_image TEXT,
  price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,
  total NUMERIC NOT NULL
);

-- 6. BẢNG TIN NHẮN CHAT REAL-TIME
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL,
  sender_role TEXT NOT NULL,
  sender_phone TEXT NOT NULL,
  sender_name TEXT NOT NULL,
  message TEXT NOT NULL,
  image_url TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. BẢNG THÔNG TIN QUÁN ĂN
CREATE TABLE IF NOT EXISTS store_settings (
  id BIGINT PRIMARY KEY DEFAULT 1,
  store_name TEXT DEFAULT 'Bếp Việt Gourmet',
  is_open BOOLEAN DEFAULT TRUE,
  hotline TEXT DEFAULT '1900 6868',
  address TEXT DEFAULT '123 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
  banner_message TEXT DEFAULT 'Chào mừng bạn đến với Bếp Việt - Giảm ngay 20.000đ cho đơn từ 150k!'
);

-- BẬT REALTIME CHO CÁC BẢNG QUAN TRỌNG TRÊN SUPABASE (Chat & Orders)
ALTER PUBLICATION supabase_realtime ADD TABLE chat_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;

-- BẬT ROW LEVEL SECURITY (RLS) VÀ TẠO CHÍNH SÁCH MỞ CHO BACKEND & NGƯỜI DÙNG
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE foods ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to categories" ON categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to foods" ON foods FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to orders" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to order_items" ON order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to chat_messages" ON chat_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to store_settings" ON store_settings FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- DỮ LIỆU MẪU BAN ĐẦU (SEED DATA)
-- ==============================================================================

-- 1. Danh mục món ăn
INSERT INTO categories (id, name, slug, icon, display_order) VALUES
(1, 'Cơm & Món Chính', 'com-mon-chinh', 'Utensils', 1),
(2, 'Phở, Bún & Mì', 'pho-bun-mi', 'Soup', 2),
(3, 'Bánh Mì & Ăn Sáng', 'banh-mi-an-sang', 'Sandwich', 3),
(4, 'Đồ Uống & Trà Sữa', 'do-uong-tra-sua', 'CupSoda', 4),
(5, 'Ăn Vặt & Khai Vị', 'an-vat-khai-vi', 'Cookie', 5),
(6, 'Tráng Miệng & Chè', 'trang-mieng-che', 'IceCream', 6)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, icon = EXCLUDED.icon;

-- 2. Món ăn tinh hoa ẩm thực Việt Nam
INSERT INTO foods (id, category_id, name, description, price, original_price, image, is_available, rating, prep_time, spicy_level, is_featured, sales_count) VALUES
(1, 2, 'Phở Bò Tái Lăn Hà Nội', 'Thịt bò tươi xào lăn thơm phức tỏi gừng, nước dùng hầm xương 12 tiếng ngọt thanh đậm đà, ăn kèm quẩy giòn tan.', 55000, 65000, 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80', true, 4.9, 15, 1, true, 342),
(2, 2, 'Bún Chả Nem Cua Bể Phố Cổ', 'Chả thịt nướng than hoa thơm lừng quyện nước mắm chua ngọt chuẩn vị Bắc, kèm nem cua bể giòn rụm và rau sống tươi mát.', 60000, 70000, 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80', true, 4.8, 20, 0, true, 289),
(3, 1, 'Cơm Tấm Sườn Bì Chả Đặc Biệt', 'Hạt gạo tấm thơm dẻo, sườn cốt lết ướp mật ong nướng vàng ươm, chả trứng béo ngậy, bì giòn thơm và mỡ hành tóp mỡ.', 58000, 65000, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80', true, 4.9, 15, 0, true, 512),
(4, 3, 'Bánh Mì Chảo Xíu Mại Pate Trứng', 'Chảo nóng sốt xì xèo với viên xíu mại mềm thơm, pate gan béo ngậy, trứng ốp la lòng đào và bánh mì giòn rụm.', 45000, 50000, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80', true, 4.7, 12, 1, true, 198),
(5, 5, 'Bún Đậu Mắm Tôm Thập Cẩm', 'Đậu mơ rán giòn vỏ mềm ruột, thịt bắp luộc, chả cốm nóng hổi chấm cùng mắm tôm Thanh Hóa đánh sủi bọt ngập quất.', 65000, 75000, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80', true, 4.9, 20, 1, true, 420),
(6, 5, 'Gỏi Cuốn Tôm Thịt (3 Cuốn)', 'Tôm sú tươi đỏ au, thịt ba chỉ ngọt mềm, bún và rau thơm cuốn bánh tráng dẻo, chấm sốt tương đậu phộng bùi béo.', 35000, 40000, 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80', true, 4.6, 10, 0, false, 176),
(7, 4, 'Trà Sữa Trân Châu Đường Đen', 'Sữa tươi thanh trùng béo ngậy quyện đường đen Okinawa nấu dẻo thơm và trân châu hoàng kim dai giòn sần sật.', 38000, 45000, 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=800&q=80', true, 4.8, 8, 0, true, 630),
(8, 4, 'Trà Đào Cam Sả Tươi Mát', 'Trà lài ủ lạnh thơm nức mũi kết hợp cam vàng mọng nước, sả tươi dập nhẹ và miếng đào giòn ngọt thơm.', 35000, 40000, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80', true, 4.7, 5, 0, false, 310),
(9, 4, 'Cà Phê Muối Xứ Huế', 'Cà phê phin Robusta Đắk Lắk đậm đà hòa quyện lớp kem muối biển sánh mịn bồng bềnh, ngọt ngào vị béo lẫn mằn mặn.', 29000, 35000, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80', true, 4.9, 5, 0, true, 480),
(10, 1, 'Mì Quảng Tôm Thịt Trứng Cút', 'Sợi mì vàng óng dai mềm, tôm rim đậm vị, thịt heo mềm ngọt, đậu phộng rang giòn và bánh tráng mè nướng.', 52000, 58000, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80', true, 4.8, 18, 1, false, 145),
(11, 5, 'Bánh Tráng Trộn Long An', 'Bánh tráng dẻo thấm sốt me bò cay, xoài băm, trứng cút lòng đào, khô bò đen, hành phi giòn và rau răm cay nồng.', 25000, 30000, 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80', true, 4.7, 10, 2, false, 390),
(12, 6, 'Chè Khúc Bạch Hạnh Nhân Thanh Mát', 'Từng viên khúc bạch phô mai sữa béo ngậy mềm tan trong miệng, ăn cùng nhãn lồng mọng nước, hạnh nhân rang vàng giòn.', 32000, 38000, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80', true, 4.8, 5, 0, false, 215)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, image = EXCLUDED.image;

-- 3. Tài khoản Admin & Khách hàng mẫu
INSERT INTO users (id, phone, name, address, province, district, ward, role) VALUES
(1, '0909999999', 'Chủ Quán Bếp Việt', '123 Đường Nguyễn Huệ', 'Hồ Chí Minh', 'Quận 1', 'Phường Bến Nghé', 'admin'),
(2, '0912345678', 'Nguyễn Văn An', '45 Lê Duẩn, Bến Nghé', 'Hồ Chí Minh', 'Quận 1', 'Phường Bến Nghé', 'customer')
ON CONFLICT (phone) DO NOTHING;

-- 4. Đơn hàng mẫu
INSERT INTO orders (id, order_code, user_id, customer_name, customer_phone, delivery_address, province, district, note, subtotal, discount, delivery_fee, total_amount, payment_method, status) VALUES
(1, 'ORD-2026-001', 2, 'Nguyễn Văn An', '0912345678', '45 Lê Duẩn, Bến Nghé, Quận 1', 'Hồ Chí Minh', 'Quận 1', 'Cho nhiều tương ớt và quẩy giòn nhé quán ơi!', 110000, 0, 15000, 125000, 'COD', 'preparing'),
(2, 'ORD-2026-002', 2, 'Trần Thị Mai', '0988776655', '88 Hai Bà Trưng, Tân Định, Quận 1', 'Hồ Chí Minh', 'Quận 1', 'Trà đào ít ngọt 50% đường, đá riêng', 93000, 10000, 15000, 98000, 'BANKING', 'delivering')
ON CONFLICT (id) DO NOTHING;

INSERT INTO order_items (id, order_id, food_id, food_name, food_image, price, quantity, total) VALUES
(1, 1, 1, 'Phở Bò Tái Lăn Hà Nội', 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80', 55000, 2, 110000),
(2, 2, 3, 'Cơm Tấm Sườn Bì Chả Đặc Biệt', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80', 58000, 1, 58000),
(3, 2, 8, 'Trà Đào Cam Sả Tươi Mát', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80', 35000, 1, 35000)
ON CONFLICT (id) DO NOTHING;

-- 5. Cài đặt quán ăn
INSERT INTO store_settings (id, store_name, is_open, hotline, address, banner_message) VALUES
(1, 'Bếp Việt Gourmet', true, '1900 6868', '123 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'Chào mừng bạn đến với Bếp Việt - Giảm ngay 20.000đ cho đơn từ 150k!')
ON CONFLICT (id) DO NOTHING;

-- Tự động cập nhật sequence IDs
SELECT setval('categories_id_seq', (SELECT COALESCE(MAX(id), 1) FROM categories));
SELECT setval('foods_id_seq', (SELECT COALESCE(MAX(id), 1) FROM foods));
SELECT setval('users_id_seq', (SELECT COALESCE(MAX(id), 1) FROM users));
SELECT setval('orders_id_seq', (SELECT COALESCE(MAX(id), 1) FROM orders));
SELECT setval('order_items_id_seq', (SELECT COALESCE(MAX(id), 1) FROM order_items));
SELECT setval('chat_messages_id_seq', (SELECT COALESCE(MAX(id), 1) FROM chat_messages));
